# Generated by Django 2.2.16 on 2021-03-18 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='data_posted',
            new_name='date_posted',
        ),
    ]
