# Generated by Django 2.2.16 on 2021-03-15 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210315_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='<django.db.models.query_utils.DeferredAttribute object at 0x7f875c210fa0>', max_length=254),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x7f875c210ee0>', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='User.first_name', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x7f875c210e20>', max_length=10),
        ),
    ]
