# Generated by Django 2.2.16 on 2021-03-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='encryption',
            field=models.CharField(choices=[(1, 'IVK & PIN'), (2, 'IVK Only'), (3, 'Pin Only'), (4, 'None')], default=1, max_length=20),
        ),
        migrations.AlterField(
            model_name='files',
            name='pin',
            field=models.CharField(default='yhjWDdALhh', max_length=20),
        ),
    ]
