# Generated by Django 2.2.16 on 2021-03-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0002_auto_20210325_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='encryption',
            field=models.CharField(choices=[('IVK & Pin', 'IVK & PIN'), ('IVK Only', 'IVK Only'), ('Pin Only', 'Pin Only'), ('None', 'None')], default=1, max_length=20),
        ),
        migrations.AlterField(
            model_name='files',
            name='pin',
            field=models.CharField(default='nsKBGuPKvh', max_length=20),
        ),
    ]
