# Generated by Django 2.2.16 on 2021-03-25 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0003_auto_20210325_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='pin',
        ),
    ]
