# Generated by Django 2.2.16 on 2021-03-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0004_remove_files_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='pin',
            field=models.IntegerField(null=True),
        ),
    ]
