# Generated by Django 2.2.16 on 2021-03-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0005_files_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='pin',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
