# Generated by Django 2.2.16 on 2021-03-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0006_auto_20210325_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='pin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
