# Generated by Django 2.2.16 on 2021-03-30 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0007_auto_20210325_2040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='files',
            options={'permissions': (('can_view', 'can view'),)},
        ),
    ]
