# Generated by Django 2.2.16 on 2021-03-30 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0010_auto_20210330_0112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='files',
            options={},
        ),
    ]
