# Generated by Django 2.2.16 on 2021-03-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210317_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='doc',
            field=models.FileField(default='', upload_to="files/<class 'django.contrib.auth.models.User'>"),
        ),
    ]
